/**
 * @class stkCGALPoissonReconstructionMesher
 * @brief This CGAL component implements a surface reconstruction method which takes as input point sets 
 * with oriented normals and computes an implicit function. We assume that the input points contain no outliers and little noise. 
 * The output surface mesh is generated by extracting an isosurface of this function with the CGAL Surface Mesh Generatoror potentially 
 * with any other surface contouring algorithm.
 * 
 * Link: https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html
 *
 *        Inputs: Point Set
 *        Output: Surface Mesh (port 0, vtkPolyData)
 *
 * @sa
 * stkCGALPoissonReconstructionMesher
 */
#pragma once

#include <stkCGALPoissonReconstructionMesherInterface.h>
#include <stkCGALModule.h>

/**
 * @ingroup stkCGAL
 *
 */
class STKCGAL_EXPORT stkCGALPoissonReconstructionMesher : public stkCGALPoissonReconstructionMesherInterface
{
public:
  static stkCGALPoissonReconstructionMesher* New();
  vtkTypeMacro(stkCGALPoissonReconstructionMesher, stkCGALPoissonReconstructionMesherInterface);

protected:
  stkCGALPoissonReconstructionMesher() = default;
  ~stkCGALPoissonReconstructionMesher() = default;

  virtual int RequestData(vtkInformation*, vtkInformationVector**, vtkInformationVector*) override;

private:
  stkCGALPoissonReconstructionMesher(const stkCGALPoissonReconstructionMesher&) = delete;
  void operator=(const stkCGALPoissonReconstructionMesher&) = delete;
};
